[build]	
    command = "npm run build"
    base = "/opt/build/repo"
    publish = "/opt/build/repo"
[[redirects]]
    from ="/*"
    to = "/index.html"
    status = 200

[build.environment]	
    NODE_ENV = "development"	

[context.production.environment]	
    NODE_ENV = "production"