[build]	
    command = "npm run build"
    base = "/"
    build = "build"
[[redirects]]
    from ="/*"
    to = "/index.html"
    status = 200

[build.environment]	
    NODE_ENV = "development"	

[context.production.environment]	
    NODE_ENV = "production"